version: '3.8'
services:
  db:
    container_name: db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sst_001
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}