version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_sst_001

  db:
    container_name: db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sst_001
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}