CREATE SEQUENCE IF NOT EXISTS tms.tasks_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS tms.users_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS tms.roles_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS tms.comments_seq START WITH 1 INCREMENT BY 50;